---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

env:
  global:
    - secure: "fSjqnxnzwf4jgv2IERrVqw7Z9x5JYzLwo4gQMuyChJltzizluSX66C6\
      ajAss/0/i0Ml59qNbR/9JKWLYtXMw9ajc1ftXYV4kXz1XhHuzbAbpPR3qFPrA/40\
      ZK3LNZtAvyZuwgluLBk7b2J8SBFJ84jsDUYZP6IUwCeTIAYlR6BRQhohpOomX89A\
      pjtxBDqdUjUkFkW9/SlZnDF9rDnKO29CFS/GLcSdXZ4opxg6wEaKJ27U/C07pGsq\
      KQLDh4VAvMjRZBsIQ3r9Ax0q0YbRtr3a8g+LWfHik3TyUubI1oz1OJb90mCIqvBT\
      g96VzBH99jdUvnK7JkgO7j1DcNF8v8/zsTUWQzOToz/VoBf7cPURx00Eye2CLcSY\
      TDKfEWrqiT84IubfMO1njoa00kowMF92aOqm6L81FJRgQu4Eowuw8bWHM0T/LX85\
      1y0u/nW2unJJPew0cVYn6So6DGAwrJOdlvMNN3cjCev5OHJcJijhWeLW046ju9f1\
      W4/q2kdowZVtRl8eHBxbdH2EMJzHObIq6j2cgahk5iXPzw2B0FcffrIioUc3qigr\
      seZTZvRrcPUxST8sslUPiq20iVvoYM8rzqT2E0LYVkb1Psu3wZxsEKtdl3NRLteW\
      pQ5CylKXkWms4aZlJL7yklhn2FzMxT4l9NgQ4sGMILu4q7qMhl3U="
    - secure: "skMGhnqwgvMEODbNQt7+76z6VjEyt14oEtavoRw1Xi63ll12gle48ve\
      8jUJtEcW6gf06RnH7l5LxqBvHCz/bVLxaZ0+fVNi95m4/PUEBeSXbtmj1UsaRApc\
      CKV0hbTlPoE58oPc+hZAM6DdgkBnG+mg5VOcYZo4H3TZNjJ11aNCwo349kjUvlyH\
      H1vKe3YrlFuAJ0BOIqsTk4y0zijexGgkVUeVSzoNZ8+W8l+BVf/nJA+1RcnKbK4e\
      wcKu2/ROLmheXR9kjcehZ2USSHwynGlrspypmuRVUlupiryykFUl/nhTXODsH/0U\
      Fx2XDI7yDqFTbsZn+WUFEvVQY8kdisJ4dwJpeRTm4nJpN8whUpPjBq634ZYLupit\
      3GwhnKamGM9COidqoFgUQhBOSs4NBxo3u4gVqX56xZvEyLJGqgsoui6Xf0KYDxSY\
      sdYuCi+1+g5kLkWnCManPYlNBZfe5UWKvF5STvDVVPtL0F8t9xKwCTmrdlsOQFEG\
      Yd6VbeDUSxImCOsVPHD9lzOXZUIiGOEUfwTKtB7j+af9kybXbMxIxOCQHEbdZf+S\
      QK96w0zRZmf+Wc264mhRmTEnZxTE00Kz6k+t4DP7jIFHVUDbmn3/1f7MKVUUBnIm\
      uR+3SVuI28C9bwwvkEerTKJ732Y/41al4kssAvexX4Z6tYr8YxLk="
    - secure: "Tat++o71fCz4sNQk6FjKN9gLofRKqt5nxmPGPfK3s35RlYFrnT9iBkI\
      3bevFOqNI3/B9rgZe3i4gekzmhW1KJ0TSqypLqEBaIxPImAYsI6o9M4C+5qLSuxN\
      N0TbgHTitYJbT8bymYwdjJlbYCtZ7woYUsfUpfmCmpGliOUBVoOLuaGG7SQ3Um4t\
      WmNHNQmnD+6WP48yTevSNXJlALxwmb+Zg57C9wWoW6izrsBmeny/LzYzAl6gGVqF\
      pQD4DApEEHeyR1CKwynNpVy0jY4FZYJ2yw8ah5um8auU5gjKwMgtr2zxWKdMkPUG\
      m8gHT3Z3Nen8AlbnO+9J6ScKMg1bAf4KwGRve2VNZ9l9NQy831z56h+2xUD9oSP2\
      UlAdIbsoOcwTQNZ8ULrqY0eQsOZC693/DwGToDR9meAzF92EIqI3aBAvovVtMwi2\
      AW0S3lctII24FznVLBMemr0Fj656AeVMy2IV49dcbvLC7ny0QAe9m+vTlrbLWsOb\
      dpGdY3gylrAex3Wd75MZnYNuWqLnGQs6lWvpzr7FRvCAKn988kYTY3TQL2hkps56\
      xjeo73tLjP7zk/4pmJLvkCbzMxFpnFFldGYim6fQkya+KP6mRl8d3kGE5xUJf9qz\
      ZSzDDoBeEKo+IW2a/FpHioOnYHUyXCfg2mntc3QqK/z4bQHxmNN4="

# Install terraform and terraform-doc
before_install:
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.1/terraform_0.12.1_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - go get github.com/segmentio/terraform-docs

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt

script:
  - pre-commit run --all-files
  - molecule test
