---
# tasks file for cyhy_runner
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install system versions of the Python packages that cyhy-runner needs
  ansible.builtin.package:
    name: "{{ packages }}"

- name: Install the cyhy-runner package
  ansible.builtin.pip:
    executable: pip3
    # The extra argument is necessary on Debian 12, which correctly
    # recognizes that the local Python is externally managed
    # (i.e. managed via the system package manager and not by pip).
    # The extra argument is understood by pip on Debian 12 and Kali
    # systems, but not others.
    extra_args: "{{ (ansible_distribution == 'Kali' or (ansible_distribution == 'Debian' and ansible_distribution_release == 'bookworm')) | ternary('--break-system-packages', omit) }}"
    name: https://api.github.com/repos/cisagov/cyhy-runner/tarball/develop

- name: Create some directories that cyhy-runner requires
  ansible.builtin.file:
    mode: 0755
    path: "{{ item }}"
    state: directory
  loop:
    - /var/cyhy/runner
    - /var/log/cyhy

# Copy the systemd unit file
- name: Copy the systemd unit file for cyhy-runner
  ansible.builtin.copy:
    dest: /lib/systemd/system/cyhy-runner.service
    mode: 0644
    src: cyhy-runner.service

# Enable cyhy-runner
- name: Enable cyhy-runner
  ansible.builtin.service:
    enabled: yes
    name: cyhy-runner
