---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install pipx
  ansible.builtin.package:
    name: pipx

- name: Install system versions of the Python packages that cyhy-runner needs
  ansible.builtin.package:
    name: "{{ packages }}"

- name: Install cyhy-runner with pipx
  community.general.pipx:
    name: cyhy-runner
    source: >-
      https://api.github.com/repos/cisagov/cyhy-runner/tarball/{{ cyhy_runner_version }}
    # We want to use any Python packages that are installed on the system
    system_site_packages: true
  tags:
    # This module is not idempotent when using the source parameter
    - molecule-idempotence-notest

- name: Create some directories that cyhy-runner requires
  ansible.builtin.file:
    group: "{{ cyhy_runner_file_owner_group | default(omit) }}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ cyhy_runner_file_owner_username | default(omit) }}"
    path: "{{ item }}"
    state: directory
  loop:
    - /var/cyhy/runner
    - /var/cyhy/runner/done
    - /var/cyhy/runner/running
    - /var/log/cyhy

# Copy the systemd unit file
- name: Copy the systemd unit file for cyhy-runner
  ansible.builtin.copy:
    dest: /lib/systemd/system/cyhy-runner.service
    mode: u=rw,g=r,o=r
    src: cyhy-runner.service

# Enable cyhy-runner
- name: Enable cyhy-runner
  ansible.builtin.service:
    enabled: true
    name: cyhy-runner
