---
# boto3 and systemd are installed anywhere we would be applying this
# Ansible role
- name: Prepare
  hosts: all
  roles:
    - pip
  tasks:
    - name: Install boto3
      pip:
        name: boto3
    - name: Install systemctl
      package:
        name: systemd
        state: present
